name: Build Extension

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Package extension
      run: |
        chmod +x package.sh
        ./package.sh

    - uses: actions/upload-artifact@master
      with:
        name: extension
        path: dist